development:
  adapter: postgresql
  encoding: unicode
  database: dbyardsail
  pool: 5
  username: postgres
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: dbtest
  pool: 5
  username: postgres
  password: